// Mocks generated by Mockito 5.0.7 from annotations
// in moniepoint_flutter/test/app_notification_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:moniepoint_flutter/app/notifications/model/data/remote_notification_message.dart'
    as _i4;
import 'package:moniepoint_flutter/app/notifications/model/handlers/notification_handler.dart'
    as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [NotificationHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationHandler extends _i1.Mock
    implements _i2.NotificationHandler {
  MockNotificationHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> notify(int? notificationType) =>
      (super.noSuchMethod(Invocation.method(#notify, [notificationType]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> handle() =>
      (super.noSuchMethod(Invocation.method(#handle, []),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  void setRemoteNotificationMessage(
          _i4.RemoteNotificationMessage<dynamic>? message) =>
      super.noSuchMethod(
          Invocation.method(#setRemoteNotificationMessage, [message]),
          returnValueForMissingStub: null);
  @override
  void saveNotificationForLater(_i4.MessageType? messageType,
          _i4.RemoteNotificationMessage<dynamic>? message) =>
      super.noSuchMethod(
          Invocation.method(#saveNotificationForLater, [messageType, message]),
          returnValueForMissingStub: null);
}
