// Mocks generated by Mockito 5.0.3 from annotations
// in moniepoint_flutter/test/onboarding_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:moniepoint_flutter/app/managebeneficiaries/transfer/transfer_beneficiary.dart'
    as _i5;
import 'package:moniepoint_flutter/app/onboarding/model/data/account_info_request.dart'
    as _i6;
import 'package:moniepoint_flutter/app/onboarding/model/onboarding_service.dart'
    as _i3;
import 'package:moniepoint_flutter/core/network/service_result.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeServiceResult<ResultType> extends _i1.Fake
    implements _i2.ServiceResult<ResultType> {}

/// A class which mocks [OnBoardingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnBoardingService extends _i1.Mock implements _i3.OnBoardingService {
  MockOnBoardingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ServiceResult<_i5.TransferBeneficiary>> getAccount(
          _i6.AccountInfoRequestBody? requestBody) =>
      (super.noSuchMethod(Invocation.method(#getAccount, [requestBody]),
              returnValue:
                  Future.value(_FakeServiceResult<_i5.TransferBeneficiary>()))
          as _i4.Future<_i2.ServiceResult<_i5.TransferBeneficiary>>);
}
