// Mocks generated by Mockito 5.0.3 from annotations
// in moniepoint_flutter/test/security_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:moniepoint_flutter/app/securityquestion/model/data/security_question.dart'
    as _i5;
import 'package:moniepoint_flutter/app/securityquestion/model/security_question_service.dart'
    as _i3;
import 'package:moniepoint_flutter/core/network/service_result.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeServiceResult<ResultType> extends _i1.Fake
    implements _i2.ServiceResult<ResultType> {}

/// A class which mocks [SecurityQuestionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecurityQuestionService extends _i1.Mock
    implements _i3.SecurityQuestionService {
  MockSecurityQuestionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ServiceResult<List<_i5.SecurityQuestion>>> getAllQuestions() =>
      (super.noSuchMethod(Invocation.method(#getAllQuestions, []),
              returnValue: Future.value(
                  _FakeServiceResult<List<_i5.SecurityQuestion>>()))
          as _i4.Future<_i2.ServiceResult<List<_i5.SecurityQuestion>>>);
}
