
import 'package:moniepoint_flutter/app/savings/model/data/savings_product.dart';
import 'package:moniepoint_flutter/app/savings/model/savings_product_service.dart';
import 'package:moniepoint_flutter/app/savings/modules/flex/model/flex_saving.dart';
import 'package:moniepoint_flutter/core/network/network_bound_resource.dart';
import 'package:moniepoint_flutter/core/network/resource.dart';
import 'package:moniepoint_flutter/core/network/service_result.dart';

///@author Paul Okeke
///
class SavingsProductServiceDelegate with NetworkResource {

  late final SavingsProductService _service;

  SavingsProductServiceDelegate(SavingsProductService service) {
    this._service = service;
  }

  Stream<Resource<SavingsProduct>> getFlexProduct() {
    return networkBoundResource(
        fetchFromLocal: () => Stream.value(null),
        fetchFromRemote: () => Future.value(ServiceResult.fromJson(mockProduct, (json) => SavingsProduct.fromJson(json as Map<String, dynamic>)))//this._service.getFlexProduct()
    );
  }

  Stream<Resource<List<FlexSaving>>> getRunningFlexSavings(int customerId) {
    return networkBoundResource(
        fetchFromLocal: () => Stream.value(null),
        fetchFromRemote: () => Future.delayed(Duration(seconds: 5), (){
          return ServiceResult.fromJson(mockSavingsFlex, (json) => (json as List).map((e) => FlexSaving.fromJson(e)).toList());
        }),//this._service.getRunningFlexSavings(customerId)
    );
  }

  Stream<Resource<FlexSaving>> enableFlexSaving(int customerId) {
    return networkBoundResource(
        fetchFromLocal: () => Stream.value(null),
        fetchFromRemote: () => this._service.enableFlexSavings(
            customerId,
            "1.0.0"
        )
    );
  }
}

final mockProduct = {
  "success": true,
  "result": {
    "id": 1,
    "createdOn": "2021-11-02T12:01:18.000+0000",
    "lastModifiedOn": "2021-11-02T13:01:18",
    "deleted": false,
    "createdBy": "SYSTEM",
    "lastModifiedBy": "SYSTEM",
    "version": 0,
    "name": "Flex Savings",
    "shortDescription": "For Emergencies & General Savings",
    "longDescription": "",
    "icon": "",
    "headerImage": "",
    "code": "FLEX-SAV",
    "cbaSavingsAccountSchemeCode": "",
    "interestRate": 10.5,
    "penalties": 2
  },
  "errors": []
};

final mockSavingsFlex = {
  "success": true,
  "result": [
    // {
    //   "id": 1,
    //   "createdOn": "2021-11-03T12:25:59.000+0000",
    //   "lastModifiedOn": "2021-11-03T13:25:59",
    //   "deleted": false,
    //   "createdBy": "22951789003",
    //   "lastModifiedBy": "22951789003",
    //   "version": 0,
    //   "customer": {
    //     "id": 10,
    //     "name": "AGHO ADRIAN ",
    //     "description": null,
    //     "primaryCbaCustomerId": "1348799653315575808",
    //     "email": "oloruntobatoba@test.com",
    //     "mobileNo": "2348091614127",
    //     "timeAdded": "2021-01-12T03:11:09.681",
    //     "active": true,
    //     "title": "Mr",
    //     "headOffice": null,
    //     "relationshipManagerUserId": null,
    //     "relationshipManagerNodeGuid": null,
    //     "onBoardingBvn": "22951789003",
    //     "agentUserId": "Agent001",
    //     "onboardingStatus": "COMPLETE",
    //     "onboardingFormUUID": "Pytuyi78nuuh1921",
    //     "gender": "MALE",
    //     "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //     "dateOfBirth": "2001-01-12",
    //     "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //     "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "accountNumbers": null,
    //     "passportFileDTO": null,
    //     "hasSuppliedAddressInfo": true,
    //     "hasSuppliedAddressProof": false,
    //     "hasSuppliedIdentificationInfo": false,
    //     "hasSuppliedIdentificationProof": false,
    //     "hasSuppliedAdditionalInfo": true,
    //     "hasSuppliedNextOfKinInfo": true,
    //     "reuploadID": true,
    //     "reuploadIDDeclineReason": null,
    //     "reuploadProofOfAddress": true,
    //     "reuploadProofOfAddressDeclineReason": null,
    //     "agentProvidingAddressProof": false,
    //     "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "generatedAgentAddressProofLatitude": null,
    //     "generatedAgentAddressProofLongitude": null,
    //     "addressProofFromCBA": null,
    //     "identificationScannedImageFromCBA": null,
    //     "customerIDInfo": null,
    //     "customerAddressInfo": null,
    //     "addressFileDTO": null,
    //     "identificationFileDTO": null,
    //     "addressVisitationFormFileDTO": null,
    //     "generatedAddressFileDTO": null,
    //     "verifiedAddressFileDTO": null,
    //     "verifiedIdentificationFileDTO": null,
    //     "branchName": null,
    //     "bvnVerified": false,
    //     "addressVerified": true,
    //     "identificationVerified": true,
    //     "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "branchCode": null,
    //     "emailAddresseeMap": {
    //       "oloruntobatoba@test.com": "AGHO ADRIAN "
    //     }
    //   },
    //   "flexVersion": "1.0.0",
    //   "cbaAccountNuban": "8000001489",
    //   "interestRate": 0,
    //   "totalSavings": 0,
    //   "totalAccruedInterest": 0,
    //   "totalAppliedPenalties": 0,
    //   "flexSavingConfig": {
    //     "id": 2,
    //     "createdOn": "2021-11-03T12:25:18.000+0000",
    //     "lastModifiedOn": "2021-11-03T13:25:18",
    //     "deleted": false,
    //     "createdBy": "22951789003",
    //     "lastModifiedBy": "22951789003",
    //     "version": 0,
    //     "flexSaveType": "AUTOMATIC",
    //     "flexSaveMode": "WEEKLY",
    //     "contributionWeekDay": "MONDAY",
    //     "contributionMonthDay": 0,
    //     "duration": 1,
    //     "contributionAmount": 1000,
    //     "contributionAccount": {
    //       "id": 4,
    //       "customer": {
    //         "id": 10,
    //         "name": "AGHO ADRIAN ",
    //         "description": null,
    //         "primaryCbaCustomerId": "1348799653315575808",
    //         "email": "oloruntobatoba@test.com",
    //         "mobileNo": "2348091614127",
    //         "timeAdded": "2021-01-12T03:11:09.681",
    //         "active": true,
    //         "title": "Mr",
    //         "headOffice": null,
    //         "relationshipManagerUserId": null,
    //         "relationshipManagerNodeGuid": null,
    //         "onBoardingBvn": "22951789003",
    //         "agentUserId": "Agent001",
    //         "onboardingStatus": "COMPLETE",
    //         "onboardingFormUUID": "Pytuyi78nuuh1921",
    //         "gender": "MALE",
    //         "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //         "dateOfBirth": "2001-01-12",
    //         "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //         "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "accountNumbers": null,
    //         "passportFileDTO": null,
    //         "hasSuppliedAddressInfo": true,
    //         "hasSuppliedAddressProof": false,
    //         "hasSuppliedIdentificationInfo": false,
    //         "hasSuppliedIdentificationProof": false,
    //         "hasSuppliedAdditionalInfo": true,
    //         "hasSuppliedNextOfKinInfo": true,
    //         "reuploadID": true,
    //         "reuploadIDDeclineReason": null,
    //         "reuploadProofOfAddress": true,
    //         "reuploadProofOfAddressDeclineReason": null,
    //         "agentProvidingAddressProof": false,
    //         "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "generatedAgentAddressProofLatitude": null,
    //         "generatedAgentAddressProofLongitude": null,
    //         "addressProofFromCBA": null,
    //         "identificationScannedImageFromCBA": null,
    //         "customerIDInfo": null,
    //         "customerAddressInfo": null,
    //         "addressFileDTO": null,
    //         "identificationFileDTO": null,
    //         "addressVisitationFormFileDTO": null,
    //         "generatedAddressFileDTO": null,
    //         "verifiedAddressFileDTO": null,
    //         "verifiedIdentificationFileDTO": null,
    //         "branchName": null,
    //         "bvnVerified": false,
    //         "addressVerified": true,
    //         "identificationVerified": true,
    //         "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "branchCode": null,
    //         "emailAddresseeMap": {
    //           "oloruntobatoba@test.com": "AGHO ADRIAN "
    //         }
    //       },
    //       "cbaCustomerId": "1348799653315575808",
    //       "bankBranchId": 1,
    //       "accountName": "AGHO ADRIAN ",
    //       "currencyCode": "NGN",
    //       "accountNumber": "8000018402",
    //       "phoneNumber": "2348155198258",
    //       "email": "peguda1@teamapt.com",
    //       "address": null,
    //       "openingDate": "2021-01-12T01:11:12",
    //       "alternateAccountNumber": null,
    //       "accountType": "SAVINGS",
    //       "bvn": "22951789003",
    //       "accountBalance": null,
    //       "schemeCode": {
    //         "id": 7,
    //         "name": "MTC5",
    //         "description": "Customer indemnity",
    //         "code": "MTC5",
    //         "accountProvider": {
    //           "id": 1,
    //           "name": "Moniepoint",
    //           "centralBankCode": "950515",
    //           "aptentRoutingKey": "950515",
    //           "country": {
    //             "id": 1,
    //             "code": "NG",
    //             "name": "Nigeria",
    //             "postCode": "234",
    //             "isoCode": null,
    //             "base64Icon": null,
    //             "active": true,
    //             "timeAdded": null,
    //             "states": null,
    //             "nationality": "Nigerian"
    //           },
    //           "customerRMNodeType": "RELATIONSHIP_MANAGER",
    //           "customerAccountRMNodeType": "RELATIONSHIP_MANAGER",
    //           "unsupportedFeatures": null
    //         },
    //         "unsupportedFeatures": [],
    //         "customerType": "RETAIL",
    //         "classification": null,
    //         "timeAdded": "2021-07-05T17:04:43.27",
    //         "defaultAccountRole": null,
    //         "schemeGroup": "MONNIFY_INDEMNITY",
    //         "groupOrder": 6
    //       },
    //       "validated": true,
    //       "relationshipManagerNodeGuid": null,
    //       "relationshipManagerUserId": null,
    //       "active": true,
    //       "unsupportedFeatures": null,
    //       "timeAdded": "2021-01-12T03:11:10",
    //       "multipleDebit": false,
    //       "operationalAccount": null,
    //       "ussdProfile": null,
    //       "blocked": false,
    //       "blockReason": null,
    //       "blockedBy": null,
    //       "blockedTime": null,
    //       "referralCode": null,
    //       "emailAddresseeMap": {
    //         "peguda1@teamapt.com": "AGHO ADRIAN ",
    //         "oloruntobatoba@test.com": "AGHO ADRIAN "
    //       }
    //     },
    //     "active": true
    //   }
    // },
    // {
    //   "id": 2,
    //   "createdOn": "2021-11-03T12:30:44.000+0000",
    //   "lastModifiedOn": "2021-11-03T13:30:44",
    //   "deleted": false,
    //   "createdBy": "22951789003",
    //   "lastModifiedBy": "22951789003",
    //   "version": 0,
    //   "customer": {
    //     "id": 10,
    //     "name": "AGHO ADRIAN ",
    //     "description": null,
    //     "primaryCbaCustomerId": "1348799653315575808",
    //     "email": "oloruntobatoba@test.com",
    //     "mobileNo": "2348091614127",
    //     "timeAdded": "2021-01-12T03:11:09.681",
    //     "active": true,
    //     "title": "Mr",
    //     "headOffice": null,
    //     "relationshipManagerUserId": null,
    //     "relationshipManagerNodeGuid": null,
    //     "onBoardingBvn": "22951789003",
    //     "agentUserId": "Agent001",
    //     "onboardingStatus": "COMPLETE",
    //     "onboardingFormUUID": "Pytuyi78nuuh1921",
    //     "gender": "MALE",
    //     "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //     "dateOfBirth": "2001-01-12",
    //     "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //     "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "accountNumbers": null,
    //     "passportFileDTO": null,
    //     "hasSuppliedAddressInfo": true,
    //     "hasSuppliedAddressProof": false,
    //     "hasSuppliedIdentificationInfo": false,
    //     "hasSuppliedIdentificationProof": false,
    //     "hasSuppliedAdditionalInfo": true,
    //     "hasSuppliedNextOfKinInfo": true,
    //     "reuploadID": true,
    //     "reuploadIDDeclineReason": null,
    //     "reuploadProofOfAddress": true,
    //     "reuploadProofOfAddressDeclineReason": null,
    //     "agentProvidingAddressProof": false,
    //     "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "generatedAgentAddressProofLatitude": null,
    //     "generatedAgentAddressProofLongitude": null,
    //     "addressProofFromCBA": null,
    //     "identificationScannedImageFromCBA": null,
    //     "customerIDInfo": null,
    //     "customerAddressInfo": null,
    //     "addressFileDTO": null,
    //     "identificationFileDTO": null,
    //     "addressVisitationFormFileDTO": null,
    //     "generatedAddressFileDTO": null,
    //     "verifiedAddressFileDTO": null,
    //     "verifiedIdentificationFileDTO": null,
    //     "branchName": null,
    //     "bvnVerified": false,
    //     "addressVerified": true,
    //     "identificationVerified": true,
    //     "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "branchCode": null,
    //     "emailAddresseeMap": {
    //       "oloruntobatoba@test.com": "AGHO ADRIAN "
    //     }
    //   },
    //   "flexVersion": "1.0.0",
    //   "cbaAccountNuban": "8000001489",
    //   "interestRate": 0,
    //   "totalSavings": 0,
    //   "totalAccruedInterest": 0,
    //   "totalAppliedPenalties": 0,
    //   "flexSavingConfig": {
    //     "id": 3,
    //     "createdOn": "2021-11-03T12:30:42.000+0000",
    //     "lastModifiedOn": "2021-11-03T13:30:42",
    //     "deleted": false,
    //     "createdBy": "22951789003",
    //     "lastModifiedBy": "22951789003",
    //     "version": 0,
    //     "flexSaveType": "AUTOMATIC",
    //     "flexSaveMode": "WEEKLY",
    //     "contributionWeekDay": "TUESDAY",
    //     "contributionMonthDay": 0,
    //     "duration": 1,
    //     "contributionAmount": 1000,
    //     "contributionAccount": {
    //       "id": 4,
    //       "customer": {
    //         "id": 10,
    //         "name": "AGHO ADRIAN ",
    //         "description": null,
    //         "primaryCbaCustomerId": "1348799653315575808",
    //         "email": "oloruntobatoba@test.com",
    //         "mobileNo": "2348091614127",
    //         "timeAdded": "2021-01-12T03:11:09.681",
    //         "active": true,
    //         "title": "Mr",
    //         "headOffice": null,
    //         "relationshipManagerUserId": null,
    //         "relationshipManagerNodeGuid": null,
    //         "onBoardingBvn": "22951789003",
    //         "agentUserId": "Agent001",
    //         "onboardingStatus": "COMPLETE",
    //         "onboardingFormUUID": "Pytuyi78nuuh1921",
    //         "gender": "MALE",
    //         "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //         "dateOfBirth": "2001-01-12",
    //         "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //         "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "accountNumbers": null,
    //         "passportFileDTO": null,
    //         "hasSuppliedAddressInfo": true,
    //         "hasSuppliedAddressProof": false,
    //         "hasSuppliedIdentificationInfo": false,
    //         "hasSuppliedIdentificationProof": false,
    //         "hasSuppliedAdditionalInfo": true,
    //         "hasSuppliedNextOfKinInfo": true,
    //         "reuploadID": true,
    //         "reuploadIDDeclineReason": null,
    //         "reuploadProofOfAddress": true,
    //         "reuploadProofOfAddressDeclineReason": null,
    //         "agentProvidingAddressProof": false,
    //         "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "generatedAgentAddressProofLatitude": null,
    //         "generatedAgentAddressProofLongitude": null,
    //         "addressProofFromCBA": null,
    //         "identificationScannedImageFromCBA": null,
    //         "customerIDInfo": null,
    //         "customerAddressInfo": null,
    //         "addressFileDTO": null,
    //         "identificationFileDTO": null,
    //         "addressVisitationFormFileDTO": null,
    //         "generatedAddressFileDTO": null,
    //         "verifiedAddressFileDTO": null,
    //         "verifiedIdentificationFileDTO": null,
    //         "branchName": null,
    //         "bvnVerified": false,
    //         "addressVerified": true,
    //         "identificationVerified": true,
    //         "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "branchCode": null,
    //         "emailAddresseeMap": {
    //           "oloruntobatoba@test.com": "AGHO ADRIAN "
    //         }
    //       },
    //       "cbaCustomerId": "1348799653315575808",
    //       "bankBranchId": 1,
    //       "accountName": "AGHO ADRIAN ",
    //       "currencyCode": "NGN",
    //       "accountNumber": "8000018402",
    //       "phoneNumber": "2348155198258",
    //       "email": "peguda1@teamapt.com",
    //       "address": null,
    //       "openingDate": "2021-01-12T01:11:12",
    //       "alternateAccountNumber": null,
    //       "accountType": "SAVINGS",
    //       "bvn": "22951789003",
    //       "accountBalance": null,
    //       "schemeCode": {
    //         "id": 7,
    //         "name": "MTC5",
    //         "description": "Customer indemnity",
    //         "code": "MTC5",
    //         "accountProvider": {
    //           "id": 1,
    //           "name": "Moniepoint",
    //           "centralBankCode": "950515",
    //           "aptentRoutingKey": "950515",
    //           "country": {
    //             "id": 1,
    //             "code": "NG",
    //             "name": "Nigeria",
    //             "postCode": "234",
    //             "isoCode": null,
    //             "base64Icon": null,
    //             "active": true,
    //             "timeAdded": null,
    //             "states": null,
    //             "nationality": "Nigerian"
    //           },
    //           "customerRMNodeType": "RELATIONSHIP_MANAGER",
    //           "customerAccountRMNodeType": "RELATIONSHIP_MANAGER",
    //           "unsupportedFeatures": null
    //         },
    //         "unsupportedFeatures": [],
    //         "customerType": "RETAIL",
    //         "classification": null,
    //         "timeAdded": "2021-07-05T17:04:43.27",
    //         "defaultAccountRole": null,
    //         "schemeGroup": "MONNIFY_INDEMNITY",
    //         "groupOrder": 6
    //       },
    //       "validated": true,
    //       "relationshipManagerNodeGuid": null,
    //       "relationshipManagerUserId": null,
    //       "active": true,
    //       "unsupportedFeatures": null,
    //       "timeAdded": "2021-01-12T03:11:10",
    //       "multipleDebit": false,
    //       "operationalAccount": null,
    //       "ussdProfile": null,
    //       "blocked": false,
    //       "blockReason": null,
    //       "blockedBy": null,
    //       "blockedTime": null,
    //       "referralCode": null,
    //       "emailAddresseeMap": {
    //         "peguda1@teamapt.com": "AGHO ADRIAN ",
    //         "oloruntobatoba@test.com": "AGHO ADRIAN "
    //       }
    //     },
    //     "active": true
    //   }
    // },
    // {
    //   "id": 3,
    //   "createdOn": "2021-11-03T12:32:27.000+0000",
    //   "lastModifiedOn": "2021-11-03T13:32:27",
    //   "deleted": false,
    //   "createdBy": "22951789003",
    //   "lastModifiedBy": "22951789003",
    //   "version": 0,
    //   "customer": {
    //     "id": 10,
    //     "name": "AGHO ADRIAN ",
    //     "description": null,
    //     "primaryCbaCustomerId": "1348799653315575808",
    //     "email": "oloruntobatoba@test.com",
    //     "mobileNo": "2348091614127",
    //     "timeAdded": "2021-01-12T03:11:09.681",
    //     "active": true,
    //     "title": "Mr",
    //     "headOffice": null,
    //     "relationshipManagerUserId": null,
    //     "relationshipManagerNodeGuid": null,
    //     "onBoardingBvn": "22951789003",
    //     "agentUserId": "Agent001",
    //     "onboardingStatus": "COMPLETE",
    //     "onboardingFormUUID": "Pytuyi78nuuh1921",
    //     "gender": "MALE",
    //     "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //     "dateOfBirth": "2001-01-12",
    //     "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //     "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "accountNumbers": null,
    //     "passportFileDTO": null,
    //     "hasSuppliedAddressInfo": true,
    //     "hasSuppliedAddressProof": false,
    //     "hasSuppliedIdentificationInfo": false,
    //     "hasSuppliedIdentificationProof": false,
    //     "hasSuppliedAdditionalInfo": true,
    //     "hasSuppliedNextOfKinInfo": true,
    //     "reuploadID": true,
    //     "reuploadIDDeclineReason": null,
    //     "reuploadProofOfAddress": true,
    //     "reuploadProofOfAddressDeclineReason": null,
    //     "agentProvidingAddressProof": false,
    //     "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "generatedAgentAddressProofLatitude": null,
    //     "generatedAgentAddressProofLongitude": null,
    //     "addressProofFromCBA": null,
    //     "identificationScannedImageFromCBA": null,
    //     "customerIDInfo": null,
    //     "customerAddressInfo": null,
    //     "addressFileDTO": null,
    //     "identificationFileDTO": null,
    //     "addressVisitationFormFileDTO": null,
    //     "generatedAddressFileDTO": null,
    //     "verifiedAddressFileDTO": null,
    //     "verifiedIdentificationFileDTO": null,
    //     "branchName": null,
    //     "bvnVerified": false,
    //     "addressVerified": true,
    //     "identificationVerified": true,
    //     "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "branchCode": null,
    //     "emailAddresseeMap": {
    //       "oloruntobatoba@test.com": "AGHO ADRIAN "
    //     }
    //   },
    //   "flexVersion": "1.0.0",
    //   "cbaAccountNuban": "8000001489",
    //   "interestRate": 0,
    //   "totalSavings": 0,
    //   "totalAccruedInterest": 0,
    //   "totalAppliedPenalties": 0,
    //   "flexSavingConfig": {
    //     "id": 4,
    //     "createdOn": "2021-11-03T12:32:25.000+0000",
    //     "lastModifiedOn": "2021-11-03T13:32:25",
    //     "deleted": false,
    //     "createdBy": "22951789003",
    //     "lastModifiedBy": "22951789003",
    //     "version": 0,
    //     "flexSaveType": "AUTOMATIC",
    //     "flexSaveMode": "WEEKLY",
    //     "contributionWeekDay": "WEDNESDAY",
    //     "contributionMonthDay": 0,
    //     "duration": 1,
    //     "contributionAmount": 1000,
    //     "contributionAccount": {
    //       "id": 4,
    //       "customer": {
    //         "id": 10,
    //         "name": "AGHO ADRIAN ",
    //         "description": null,
    //         "primaryCbaCustomerId": "1348799653315575808",
    //         "email": "oloruntobatoba@test.com",
    //         "mobileNo": "2348091614127",
    //         "timeAdded": "2021-01-12T03:11:09.681",
    //         "active": true,
    //         "title": "Mr",
    //         "headOffice": null,
    //         "relationshipManagerUserId": null,
    //         "relationshipManagerNodeGuid": null,
    //         "onBoardingBvn": "22951789003",
    //         "agentUserId": "Agent001",
    //         "onboardingStatus": "COMPLETE",
    //         "onboardingFormUUID": "Pytuyi78nuuh1921",
    //         "gender": "MALE",
    //         "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //         "dateOfBirth": "2001-01-12",
    //         "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //         "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "accountNumbers": null,
    //         "passportFileDTO": null,
    //         "hasSuppliedAddressInfo": true,
    //         "hasSuppliedAddressProof": false,
    //         "hasSuppliedIdentificationInfo": false,
    //         "hasSuppliedIdentificationProof": false,
    //         "hasSuppliedAdditionalInfo": true,
    //         "hasSuppliedNextOfKinInfo": true,
    //         "reuploadID": true,
    //         "reuploadIDDeclineReason": null,
    //         "reuploadProofOfAddress": true,
    //         "reuploadProofOfAddressDeclineReason": null,
    //         "agentProvidingAddressProof": false,
    //         "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "generatedAgentAddressProofLatitude": null,
    //         "generatedAgentAddressProofLongitude": null,
    //         "addressProofFromCBA": null,
    //         "identificationScannedImageFromCBA": null,
    //         "customerIDInfo": null,
    //         "customerAddressInfo": null,
    //         "addressFileDTO": null,
    //         "identificationFileDTO": null,
    //         "addressVisitationFormFileDTO": null,
    //         "generatedAddressFileDTO": null,
    //         "verifiedAddressFileDTO": null,
    //         "verifiedIdentificationFileDTO": null,
    //         "branchName": null,
    //         "bvnVerified": false,
    //         "addressVerified": true,
    //         "identificationVerified": true,
    //         "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "branchCode": null,
    //         "emailAddresseeMap": {
    //           "oloruntobatoba@test.com": "AGHO ADRIAN "
    //         }
    //       },
    //       "cbaCustomerId": "1348799653315575808",
    //       "bankBranchId": 1,
    //       "accountName": "AGHO ADRIAN ",
    //       "currencyCode": "NGN",
    //       "accountNumber": "8000018402",
    //       "phoneNumber": "2348155198258",
    //       "email": "peguda1@teamapt.com",
    //       "address": null,
    //       "openingDate": "2021-01-12T01:11:12",
    //       "alternateAccountNumber": null,
    //       "accountType": "SAVINGS",
    //       "bvn": "22951789003",
    //       "accountBalance": null,
    //       "schemeCode": {
    //         "id": 7,
    //         "name": "MTC5",
    //         "description": "Customer indemnity",
    //         "code": "MTC5",
    //         "accountProvider": {
    //           "id": 1,
    //           "name": "Moniepoint",
    //           "centralBankCode": "950515",
    //           "aptentRoutingKey": "950515",
    //           "country": {
    //             "id": 1,
    //             "code": "NG",
    //             "name": "Nigeria",
    //             "postCode": "234",
    //             "isoCode": null,
    //             "base64Icon": null,
    //             "active": true,
    //             "timeAdded": null,
    //             "states": null,
    //             "nationality": "Nigerian"
    //           },
    //           "customerRMNodeType": "RELATIONSHIP_MANAGER",
    //           "customerAccountRMNodeType": "RELATIONSHIP_MANAGER",
    //           "unsupportedFeatures": null
    //         },
    //         "unsupportedFeatures": [],
    //         "customerType": "RETAIL",
    //         "classification": null,
    //         "timeAdded": "2021-07-05T17:04:43.27",
    //         "defaultAccountRole": null,
    //         "schemeGroup": "MONNIFY_INDEMNITY",
    //         "groupOrder": 6
    //       },
    //       "validated": true,
    //       "relationshipManagerNodeGuid": null,
    //       "relationshipManagerUserId": null,
    //       "active": true,
    //       "unsupportedFeatures": null,
    //       "timeAdded": "2021-01-12T03:11:10",
    //       "multipleDebit": false,
    //       "operationalAccount": null,
    //       "ussdProfile": null,
    //       "blocked": false,
    //       "blockReason": null,
    //       "blockedBy": null,
    //       "blockedTime": null,
    //       "referralCode": null,
    //       "emailAddresseeMap": {
    //         "peguda1@teamapt.com": "AGHO ADRIAN ",
    //         "oloruntobatoba@test.com": "AGHO ADRIAN "
    //       }
    //     },
    //     "active": true
    //   }
    // },
    // {
    //   "id": 4,
    //   "createdOn": "2021-11-03T12:34:21.000+0000",
    //   "lastModifiedOn": "2021-11-03T13:34:21",
    //   "deleted": false,
    //   "createdBy": "22951789003",
    //   "lastModifiedBy": "22951789003",
    //   "version": 0,
    //   "customer": {
    //     "id": 10,
    //     "name": "AGHO ADRIAN ",
    //     "description": null,
    //     "primaryCbaCustomerId": "1348799653315575808",
    //     "email": "oloruntobatoba@test.com",
    //     "mobileNo": "2348091614127",
    //     "timeAdded": "2021-01-12T03:11:09.681",
    //     "active": true,
    //     "title": "Mr",
    //     "headOffice": null,
    //     "relationshipManagerUserId": null,
    //     "relationshipManagerNodeGuid": null,
    //     "onBoardingBvn": "22951789003",
    //     "agentUserId": "Agent001",
    //     "onboardingStatus": "COMPLETE",
    //     "onboardingFormUUID": "Pytuyi78nuuh1921",
    //     "gender": "MALE",
    //     "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //     "dateOfBirth": "2001-01-12",
    //     "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //     "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "accountNumbers": null,
    //     "passportFileDTO": null,
    //     "hasSuppliedAddressInfo": true,
    //     "hasSuppliedAddressProof": false,
    //     "hasSuppliedIdentificationInfo": false,
    //     "hasSuppliedIdentificationProof": false,
    //     "hasSuppliedAdditionalInfo": true,
    //     "hasSuppliedNextOfKinInfo": true,
    //     "reuploadID": true,
    //     "reuploadIDDeclineReason": null,
    //     "reuploadProofOfAddress": true,
    //     "reuploadProofOfAddressDeclineReason": null,
    //     "agentProvidingAddressProof": false,
    //     "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "generatedAgentAddressProofLatitude": null,
    //     "generatedAgentAddressProofLongitude": null,
    //     "addressProofFromCBA": null,
    //     "identificationScannedImageFromCBA": null,
    //     "customerIDInfo": null,
    //     "customerAddressInfo": null,
    //     "addressFileDTO": null,
    //     "identificationFileDTO": null,
    //     "addressVisitationFormFileDTO": null,
    //     "generatedAddressFileDTO": null,
    //     "verifiedAddressFileDTO": null,
    //     "verifiedIdentificationFileDTO": null,
    //     "branchName": null,
    //     "bvnVerified": false,
    //     "addressVerified": true,
    //     "identificationVerified": true,
    //     "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "branchCode": null,
    //     "emailAddresseeMap": {
    //       "oloruntobatoba@test.com": "AGHO ADRIAN "
    //     }
    //   },
    //   "flexVersion": "1.0.0",
    //   "cbaAccountNuban": "8000001489",
    //   "interestRate": 0,
    //   "totalSavings": 0,
    //   "totalAccruedInterest": 0,
    //   "totalAppliedPenalties": 0,
    //   "flexSavingConfig": {
    //     "id": 5,
    //     "createdOn": "2021-11-03T12:34:08.000+0000",
    //     "lastModifiedOn": "2021-11-03T13:34:08",
    //     "deleted": false,
    //     "createdBy": "22951789003",
    //     "lastModifiedBy": "22951789003",
    //     "version": 0,
    //     "flexSaveType": "AUTOMATIC",
    //     "flexSaveMode": "WEEKLY",
    //     "contributionWeekDay": "THURSDAY",
    //     "contributionMonthDay": 0,
    //     "duration": 1,
    //     "contributionAmount": 1000,
    //     "contributionAccount": {
    //       "id": 4,
    //       "customer": {
    //         "id": 10,
    //         "name": "AGHO ADRIAN ",
    //         "description": null,
    //         "primaryCbaCustomerId": "1348799653315575808",
    //         "email": "oloruntobatoba@test.com",
    //         "mobileNo": "2348091614127",
    //         "timeAdded": "2021-01-12T03:11:09.681",
    //         "active": true,
    //         "title": "Mr",
    //         "headOffice": null,
    //         "relationshipManagerUserId": null,
    //         "relationshipManagerNodeGuid": null,
    //         "onBoardingBvn": "22951789003",
    //         "agentUserId": "Agent001",
    //         "onboardingStatus": "COMPLETE",
    //         "onboardingFormUUID": "Pytuyi78nuuh1921",
    //         "gender": "MALE",
    //         "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //         "dateOfBirth": "2001-01-12",
    //         "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //         "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "accountNumbers": null,
    //         "passportFileDTO": null,
    //         "hasSuppliedAddressInfo": true,
    //         "hasSuppliedAddressProof": false,
    //         "hasSuppliedIdentificationInfo": false,
    //         "hasSuppliedIdentificationProof": false,
    //         "hasSuppliedAdditionalInfo": true,
    //         "hasSuppliedNextOfKinInfo": true,
    //         "reuploadID": true,
    //         "reuploadIDDeclineReason": null,
    //         "reuploadProofOfAddress": true,
    //         "reuploadProofOfAddressDeclineReason": null,
    //         "agentProvidingAddressProof": false,
    //         "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "generatedAgentAddressProofLatitude": null,
    //         "generatedAgentAddressProofLongitude": null,
    //         "addressProofFromCBA": null,
    //         "identificationScannedImageFromCBA": null,
    //         "customerIDInfo": null,
    //         "customerAddressInfo": null,
    //         "addressFileDTO": null,
    //         "identificationFileDTO": null,
    //         "addressVisitationFormFileDTO": null,
    //         "generatedAddressFileDTO": null,
    //         "verifiedAddressFileDTO": null,
    //         "verifiedIdentificationFileDTO": null,
    //         "branchName": null,
    //         "bvnVerified": false,
    //         "addressVerified": true,
    //         "identificationVerified": true,
    //         "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "branchCode": null,
    //         "emailAddresseeMap": {
    //           "oloruntobatoba@test.com": "AGHO ADRIAN "
    //         }
    //       },
    //       "cbaCustomerId": "1348799653315575808",
    //       "bankBranchId": 1,
    //       "accountName": "AGHO ADRIAN ",
    //       "currencyCode": "NGN",
    //       "accountNumber": "8000018402",
    //       "phoneNumber": "2348155198258",
    //       "email": "peguda1@teamapt.com",
    //       "address": null,
    //       "openingDate": "2021-01-12T01:11:12",
    //       "alternateAccountNumber": null,
    //       "accountType": "SAVINGS",
    //       "bvn": "22951789003",
    //       "accountBalance": null,
    //       "schemeCode": {
    //         "id": 7,
    //         "name": "MTC5",
    //         "description": "Customer indemnity",
    //         "code": "MTC5",
    //         "accountProvider": {
    //           "id": 1,
    //           "name": "Moniepoint",
    //           "centralBankCode": "950515",
    //           "aptentRoutingKey": "950515",
    //           "country": {
    //             "id": 1,
    //             "code": "NG",
    //             "name": "Nigeria",
    //             "postCode": "234",
    //             "isoCode": null,
    //             "base64Icon": null,
    //             "active": true,
    //             "timeAdded": null,
    //             "states": null,
    //             "nationality": "Nigerian"
    //           },
    //           "customerRMNodeType": "RELATIONSHIP_MANAGER",
    //           "customerAccountRMNodeType": "RELATIONSHIP_MANAGER",
    //           "unsupportedFeatures": null
    //         },
    //         "unsupportedFeatures": [],
    //         "customerType": "RETAIL",
    //         "classification": null,
    //         "timeAdded": "2021-07-05T17:04:43.27",
    //         "defaultAccountRole": null,
    //         "schemeGroup": "MONNIFY_INDEMNITY",
    //         "groupOrder": 6
    //       },
    //       "validated": true,
    //       "relationshipManagerNodeGuid": null,
    //       "relationshipManagerUserId": null,
    //       "active": true,
    //       "unsupportedFeatures": null,
    //       "timeAdded": "2021-01-12T03:11:10",
    //       "multipleDebit": false,
    //       "operationalAccount": null,
    //       "ussdProfile": null,
    //       "blocked": false,
    //       "blockReason": null,
    //       "blockedBy": null,
    //       "blockedTime": null,
    //       "referralCode": null,
    //       "emailAddresseeMap": {
    //         "peguda1@teamapt.com": "AGHO ADRIAN ",
    //         "oloruntobatoba@test.com": "AGHO ADRIAN "
    //       }
    //     },
    //     "active": true
    //   }
    // },
    // {
    //   "id": 5,
    //   "createdOn": "2021-11-03T12:36:10.000+0000",
    //   "lastModifiedOn": "2021-11-03T13:36:10",
    //   "deleted": false,
    //   "createdBy": "22951789003",
    //   "lastModifiedBy": "22951789003",
    //   "version": 0,
    //   "customer": {
    //     "id": 10,
    //     "name": "AGHO ADRIAN ",
    //     "description": null,
    //     "primaryCbaCustomerId": "1348799653315575808",
    //     "email": "oloruntobatoba@test.com",
    //     "mobileNo": "2348091614127",
    //     "timeAdded": "2021-01-12T03:11:09.681",
    //     "active": true,
    //     "title": "Mr",
    //     "headOffice": null,
    //     "relationshipManagerUserId": null,
    //     "relationshipManagerNodeGuid": null,
    //     "onBoardingBvn": "22951789003",
    //     "agentUserId": "Agent001",
    //     "onboardingStatus": "COMPLETE",
    //     "onboardingFormUUID": "Pytuyi78nuuh1921",
    //     "gender": "MALE",
    //     "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //     "dateOfBirth": "2001-01-12",
    //     "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //     "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "accountNumbers": null,
    //     "passportFileDTO": null,
    //     "hasSuppliedAddressInfo": true,
    //     "hasSuppliedAddressProof": false,
    //     "hasSuppliedIdentificationInfo": false,
    //     "hasSuppliedIdentificationProof": false,
    //     "hasSuppliedAdditionalInfo": true,
    //     "hasSuppliedNextOfKinInfo": true,
    //     "reuploadID": true,
    //     "reuploadIDDeclineReason": null,
    //     "reuploadProofOfAddress": true,
    //     "reuploadProofOfAddressDeclineReason": null,
    //     "agentProvidingAddressProof": false,
    //     "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "generatedAgentAddressProofLatitude": null,
    //     "generatedAgentAddressProofLongitude": null,
    //     "addressProofFromCBA": null,
    //     "identificationScannedImageFromCBA": null,
    //     "customerIDInfo": null,
    //     "customerAddressInfo": null,
    //     "addressFileDTO": null,
    //     "identificationFileDTO": null,
    //     "addressVisitationFormFileDTO": null,
    //     "generatedAddressFileDTO": null,
    //     "verifiedAddressFileDTO": null,
    //     "verifiedIdentificationFileDTO": null,
    //     "branchName": null,
    //     "bvnVerified": false,
    //     "addressVerified": true,
    //     "identificationVerified": true,
    //     "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "branchCode": null,
    //     "emailAddresseeMap": {
    //       "oloruntobatoba@test.com": "AGHO ADRIAN "
    //     }
    //   },
    //   "flexVersion": "1.0.0",
    //   "cbaAccountNuban": "8000001489",
    //   "interestRate": 0,
    //   "totalSavings": 0,
    //   "totalAccruedInterest": 0,
    //   "totalAppliedPenalties": 0,
    //   "flexSavingConfig": {
    //     "id": 6,
    //     "createdOn": "2021-11-03T12:36:08.000+0000",
    //     "lastModifiedOn": "2021-11-03T13:36:08",
    //     "deleted": false,
    //     "createdBy": "22951789003",
    //     "lastModifiedBy": "22951789003",
    //     "version": 0,
    //     "flexSaveType": "AUTOMATIC",
    //     "flexSaveMode": "WEEKLY",
    //     "contributionWeekDay": "FRIDAY",
    //     "contributionMonthDay": 0,
    //     "duration": 1,
    //     "contributionAmount": 1001,
    //     "contributionAccount": {
    //       "id": 4,
    //       "customer": {
    //         "id": 10,
    //         "name": "AGHO ADRIAN ",
    //         "description": null,
    //         "primaryCbaCustomerId": "1348799653315575808",
    //         "email": "oloruntobatoba@test.com",
    //         "mobileNo": "2348091614127",
    //         "timeAdded": "2021-01-12T03:11:09.681",
    //         "active": true,
    //         "title": "Mr",
    //         "headOffice": null,
    //         "relationshipManagerUserId": null,
    //         "relationshipManagerNodeGuid": null,
    //         "onBoardingBvn": "22951789003",
    //         "agentUserId": "Agent001",
    //         "onboardingStatus": "COMPLETE",
    //         "onboardingFormUUID": "Pytuyi78nuuh1921",
    //         "gender": "MALE",
    //         "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //         "dateOfBirth": "2001-01-12",
    //         "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //         "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "accountNumbers": null,
    //         "passportFileDTO": null,
    //         "hasSuppliedAddressInfo": true,
    //         "hasSuppliedAddressProof": false,
    //         "hasSuppliedIdentificationInfo": false,
    //         "hasSuppliedIdentificationProof": false,
    //         "hasSuppliedAdditionalInfo": true,
    //         "hasSuppliedNextOfKinInfo": true,
    //         "reuploadID": true,
    //         "reuploadIDDeclineReason": null,
    //         "reuploadProofOfAddress": true,
    //         "reuploadProofOfAddressDeclineReason": null,
    //         "agentProvidingAddressProof": false,
    //         "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "generatedAgentAddressProofLatitude": null,
    //         "generatedAgentAddressProofLongitude": null,
    //         "addressProofFromCBA": null,
    //         "identificationScannedImageFromCBA": null,
    //         "customerIDInfo": null,
    //         "customerAddressInfo": null,
    //         "addressFileDTO": null,
    //         "identificationFileDTO": null,
    //         "addressVisitationFormFileDTO": null,
    //         "generatedAddressFileDTO": null,
    //         "verifiedAddressFileDTO": null,
    //         "verifiedIdentificationFileDTO": null,
    //         "branchName": null,
    //         "bvnVerified": false,
    //         "addressVerified": true,
    //         "identificationVerified": true,
    //         "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "branchCode": null,
    //         "emailAddresseeMap": {
    //           "oloruntobatoba@test.com": "AGHO ADRIAN "
    //         }
    //       },
    //       "cbaCustomerId": "1348799653315575808",
    //       "bankBranchId": 1,
    //       "accountName": "AGHO ADRIAN ",
    //       "currencyCode": "NGN",
    //       "accountNumber": "8000018402",
    //       "phoneNumber": "2348155198258",
    //       "email": "peguda1@teamapt.com",
    //       "address": null,
    //       "openingDate": "2021-01-12T01:11:12",
    //       "alternateAccountNumber": null,
    //       "accountType": "SAVINGS",
    //       "bvn": "22951789003",
    //       "accountBalance": null,
    //       "schemeCode": {
    //         "id": 7,
    //         "name": "MTC5",
    //         "description": "Customer indemnity",
    //         "code": "MTC5",
    //         "accountProvider": {
    //           "id": 1,
    //           "name": "Moniepoint",
    //           "centralBankCode": "950515",
    //           "aptentRoutingKey": "950515",
    //           "country": {
    //             "id": 1,
    //             "code": "NG",
    //             "name": "Nigeria",
    //             "postCode": "234",
    //             "isoCode": null,
    //             "base64Icon": null,
    //             "active": true,
    //             "timeAdded": null,
    //             "states": null,
    //             "nationality": "Nigerian"
    //           },
    //           "customerRMNodeType": "RELATIONSHIP_MANAGER",
    //           "customerAccountRMNodeType": "RELATIONSHIP_MANAGER",
    //           "unsupportedFeatures": null
    //         },
    //         "unsupportedFeatures": [],
    //         "customerType": "RETAIL",
    //         "classification": null,
    //         "timeAdded": "2021-07-05T17:04:43.27",
    //         "defaultAccountRole": null,
    //         "schemeGroup": "MONNIFY_INDEMNITY",
    //         "groupOrder": 6
    //       },
    //       "validated": true,
    //       "relationshipManagerNodeGuid": null,
    //       "relationshipManagerUserId": null,
    //       "active": true,
    //       "unsupportedFeatures": null,
    //       "timeAdded": "2021-01-12T03:11:10",
    //       "multipleDebit": false,
    //       "operationalAccount": null,
    //       "ussdProfile": null,
    //       "blocked": false,
    //       "blockReason": null,
    //       "blockedBy": null,
    //       "blockedTime": null,
    //       "referralCode": null,
    //       "emailAddresseeMap": {
    //         "peguda1@teamapt.com": "AGHO ADRIAN ",
    //         "oloruntobatoba@test.com": "AGHO ADRIAN "
    //       }
    //     },
    //     "active": true
    //   }
    // },
    // {
    //   "id": 6,
    //   "createdOn": "2021-11-03T12:37:10.000+0000",
    //   "lastModifiedOn": "2021-11-03T13:37:10",
    //   "deleted": false,
    //   "createdBy": "22951789003",
    //   "lastModifiedBy": "22951789003",
    //   "version": 0,
    //   "customer": {
    //     "id": 10,
    //     "name": "AGHO ADRIAN ",
    //     "description": null,
    //     "primaryCbaCustomerId": "1348799653315575808",
    //     "email": "oloruntobatoba@test.com",
    //     "mobileNo": "2348091614127",
    //     "timeAdded": "2021-01-12T03:11:09.681",
    //     "active": true,
    //     "title": "Mr",
    //     "headOffice": null,
    //     "relationshipManagerUserId": null,
    //     "relationshipManagerNodeGuid": null,
    //     "onBoardingBvn": "22951789003",
    //     "agentUserId": "Agent001",
    //     "onboardingStatus": "COMPLETE",
    //     "onboardingFormUUID": "Pytuyi78nuuh1921",
    //     "gender": "MALE",
    //     "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //     "dateOfBirth": "2001-01-12",
    //     "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //     "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "accountNumbers": null,
    //     "passportFileDTO": null,
    //     "hasSuppliedAddressInfo": true,
    //     "hasSuppliedAddressProof": false,
    //     "hasSuppliedIdentificationInfo": false,
    //     "hasSuppliedIdentificationProof": false,
    //     "hasSuppliedAdditionalInfo": true,
    //     "hasSuppliedNextOfKinInfo": true,
    //     "reuploadID": true,
    //     "reuploadIDDeclineReason": null,
    //     "reuploadProofOfAddress": true,
    //     "reuploadProofOfAddressDeclineReason": null,
    //     "agentProvidingAddressProof": false,
    //     "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "generatedAgentAddressProofLatitude": null,
    //     "generatedAgentAddressProofLongitude": null,
    //     "addressProofFromCBA": null,
    //     "identificationScannedImageFromCBA": null,
    //     "customerIDInfo": null,
    //     "customerAddressInfo": null,
    //     "addressFileDTO": null,
    //     "identificationFileDTO": null,
    //     "addressVisitationFormFileDTO": null,
    //     "generatedAddressFileDTO": null,
    //     "verifiedAddressFileDTO": null,
    //     "verifiedIdentificationFileDTO": null,
    //     "branchName": null,
    //     "bvnVerified": false,
    //     "addressVerified": true,
    //     "identificationVerified": true,
    //     "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "branchCode": null,
    //     "emailAddresseeMap": {
    //       "oloruntobatoba@test.com": "AGHO ADRIAN "
    //     }
    //   },
    //   "flexVersion": "1.0.0",
    //   "cbaAccountNuban": "8000001489",
    //   "interestRate": 0,
    //   "totalSavings": 0,
    //   "totalAccruedInterest": 0,
    //   "totalAppliedPenalties": 0,
    //   "flexSavingConfig": {
    //     "id": 7,
    //     "createdOn": "2021-11-03T12:37:09.000+0000",
    //     "lastModifiedOn": "2021-11-03T13:37:09",
    //     "deleted": false,
    //     "createdBy": "22951789003",
    //     "lastModifiedBy": "22951789003",
    //     "version": 0,
    //     "flexSaveType": "AUTOMATIC",
    //     "flexSaveMode": "WEEKLY",
    //     "contributionWeekDay": "SATURDAY",
    //     "contributionMonthDay": 0,
    //     "duration": 1,
    //     "contributionAmount": 1001,
    //     "contributionAccount": {
    //       "id": 4,
    //       "customer": {
    //         "id": 10,
    //         "name": "AGHO ADRIAN ",
    //         "description": null,
    //         "primaryCbaCustomerId": "1348799653315575808",
    //         "email": "oloruntobatoba@test.com",
    //         "mobileNo": "2348091614127",
    //         "timeAdded": "2021-01-12T03:11:09.681",
    //         "active": true,
    //         "title": "Mr",
    //         "headOffice": null,
    //         "relationshipManagerUserId": null,
    //         "relationshipManagerNodeGuid": null,
    //         "onBoardingBvn": "22951789003",
    //         "agentUserId": "Agent001",
    //         "onboardingStatus": "COMPLETE",
    //         "onboardingFormUUID": "Pytuyi78nuuh1921",
    //         "gender": "MALE",
    //         "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //         "dateOfBirth": "2001-01-12",
    //         "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //         "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "accountNumbers": null,
    //         "passportFileDTO": null,
    //         "hasSuppliedAddressInfo": true,
    //         "hasSuppliedAddressProof": false,
    //         "hasSuppliedIdentificationInfo": false,
    //         "hasSuppliedIdentificationProof": false,
    //         "hasSuppliedAdditionalInfo": true,
    //         "hasSuppliedNextOfKinInfo": true,
    //         "reuploadID": true,
    //         "reuploadIDDeclineReason": null,
    //         "reuploadProofOfAddress": true,
    //         "reuploadProofOfAddressDeclineReason": null,
    //         "agentProvidingAddressProof": false,
    //         "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "generatedAgentAddressProofLatitude": null,
    //         "generatedAgentAddressProofLongitude": null,
    //         "addressProofFromCBA": null,
    //         "identificationScannedImageFromCBA": null,
    //         "customerIDInfo": null,
    //         "customerAddressInfo": null,
    //         "addressFileDTO": null,
    //         "identificationFileDTO": null,
    //         "addressVisitationFormFileDTO": null,
    //         "generatedAddressFileDTO": null,
    //         "verifiedAddressFileDTO": null,
    //         "verifiedIdentificationFileDTO": null,
    //         "branchName": null,
    //         "bvnVerified": false,
    //         "addressVerified": true,
    //         "identificationVerified": true,
    //         "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "branchCode": null,
    //         "emailAddresseeMap": {
    //           "oloruntobatoba@test.com": "AGHO ADRIAN "
    //         }
    //       },
    //       "cbaCustomerId": "1348799653315575808",
    //       "bankBranchId": 1,
    //       "accountName": "AGHO ADRIAN ",
    //       "currencyCode": "NGN",
    //       "accountNumber": "8000018402",
    //       "phoneNumber": "2348155198258",
    //       "email": "peguda1@teamapt.com",
    //       "address": null,
    //       "openingDate": "2021-01-12T01:11:12",
    //       "alternateAccountNumber": null,
    //       "accountType": "SAVINGS",
    //       "bvn": "22951789003",
    //       "accountBalance": null,
    //       "schemeCode": {
    //         "id": 7,
    //         "name": "MTC5",
    //         "description": "Customer indemnity",
    //         "code": "MTC5",
    //         "accountProvider": {
    //           "id": 1,
    //           "name": "Moniepoint",
    //           "centralBankCode": "950515",
    //           "aptentRoutingKey": "950515",
    //           "country": {
    //             "id": 1,
    //             "code": "NG",
    //             "name": "Nigeria",
    //             "postCode": "234",
    //             "isoCode": null,
    //             "base64Icon": null,
    //             "active": true,
    //             "timeAdded": null,
    //             "states": null,
    //             "nationality": "Nigerian"
    //           },
    //           "customerRMNodeType": "RELATIONSHIP_MANAGER",
    //           "customerAccountRMNodeType": "RELATIONSHIP_MANAGER",
    //           "unsupportedFeatures": null
    //         },
    //         "unsupportedFeatures": [],
    //         "customerType": "RETAIL",
    //         "classification": null,
    //         "timeAdded": "2021-07-05T17:04:43.27",
    //         "defaultAccountRole": null,
    //         "schemeGroup": "MONNIFY_INDEMNITY",
    //         "groupOrder": 6
    //       },
    //       "validated": true,
    //       "relationshipManagerNodeGuid": null,
    //       "relationshipManagerUserId": null,
    //       "active": true,
    //       "unsupportedFeatures": null,
    //       "timeAdded": "2021-01-12T03:11:10",
    //       "multipleDebit": false,
    //       "operationalAccount": null,
    //       "ussdProfile": null,
    //       "blocked": false,
    //       "blockReason": null,
    //       "blockedBy": null,
    //       "blockedTime": null,
    //       "referralCode": null,
    //       "emailAddresseeMap": {
    //         "peguda1@teamapt.com": "AGHO ADRIAN ",
    //         "oloruntobatoba@test.com": "AGHO ADRIAN "
    //       }
    //     },
    //     "active": true
    //   }
    // },
    // {
    //   "id": 7,
    //   "createdOn": "2021-11-03T12:38:21.000+0000",
    //   "lastModifiedOn": "2021-11-03T13:38:21",
    //   "deleted": false,
    //   "createdBy": "22951789003",
    //   "lastModifiedBy": "22951789003",
    //   "version": 0,
    //   "customer": {
    //     "id": 10,
    //     "name": "AGHO ADRIAN ",
    //     "description": null,
    //     "primaryCbaCustomerId": "1348799653315575808",
    //     "email": "oloruntobatoba@test.com",
    //     "mobileNo": "2348091614127",
    //     "timeAdded": "2021-01-12T03:11:09.681",
    //     "active": true,
    //     "title": "Mr",
    //     "headOffice": null,
    //     "relationshipManagerUserId": null,
    //     "relationshipManagerNodeGuid": null,
    //     "onBoardingBvn": "22951789003",
    //     "agentUserId": "Agent001",
    //     "onboardingStatus": "COMPLETE",
    //     "onboardingFormUUID": "Pytuyi78nuuh1921",
    //     "gender": "MALE",
    //     "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //     "dateOfBirth": "2001-01-12",
    //     "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //     "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "accountNumbers": null,
    //     "passportFileDTO": null,
    //     "hasSuppliedAddressInfo": true,
    //     "hasSuppliedAddressProof": false,
    //     "hasSuppliedIdentificationInfo": false,
    //     "hasSuppliedIdentificationProof": false,
    //     "hasSuppliedAdditionalInfo": true,
    //     "hasSuppliedNextOfKinInfo": true,
    //     "reuploadID": true,
    //     "reuploadIDDeclineReason": null,
    //     "reuploadProofOfAddress": true,
    //     "reuploadProofOfAddressDeclineReason": null,
    //     "agentProvidingAddressProof": false,
    //     "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "generatedAgentAddressProofLatitude": null,
    //     "generatedAgentAddressProofLongitude": null,
    //     "addressProofFromCBA": null,
    //     "identificationScannedImageFromCBA": null,
    //     "customerIDInfo": null,
    //     "customerAddressInfo": null,
    //     "addressFileDTO": null,
    //     "identificationFileDTO": null,
    //     "addressVisitationFormFileDTO": null,
    //     "generatedAddressFileDTO": null,
    //     "verifiedAddressFileDTO": null,
    //     "verifiedIdentificationFileDTO": null,
    //     "branchName": null,
    //     "bvnVerified": false,
    //     "addressVerified": true,
    //     "identificationVerified": true,
    //     "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "branchCode": null,
    //     "emailAddresseeMap": {
    //       "oloruntobatoba@test.com": "AGHO ADRIAN "
    //     }
    //   },
    //   "flexVersion": "1.0.0",
    //   "cbaAccountNuban": "8000001489",
    //   "interestRate": 0,
    //   "totalSavings": 0,
    //   "totalAccruedInterest": 0,
    //   "totalAppliedPenalties": 0,
    //   "flexSavingConfig": {
    //     "id": 8,
    //     "createdOn": "2021-11-03T12:38:20.000+0000",
    //     "lastModifiedOn": "2021-11-03T13:38:20",
    //     "deleted": false,
    //     "createdBy": "22951789003",
    //     "lastModifiedBy": "22951789003",
    //     "version": 0,
    //     "flexSaveType": "AUTOMATIC",
    //     "flexSaveMode": "WEEKLY",
    //     "contributionWeekDay": "SUNDAY",
    //     "contributionMonthDay": 0,
    //     "duration": 1,
    //     "contributionAmount": 1001,
    //     "contributionAccount": {
    //       "id": 4,
    //       "customer": {
    //         "id": 10,
    //         "name": "AGHO ADRIAN ",
    //         "description": null,
    //         "primaryCbaCustomerId": "1348799653315575808",
    //         "email": "oloruntobatoba@test.com",
    //         "mobileNo": "2348091614127",
    //         "timeAdded": "2021-01-12T03:11:09.681",
    //         "active": true,
    //         "title": "Mr",
    //         "headOffice": null,
    //         "relationshipManagerUserId": null,
    //         "relationshipManagerNodeGuid": null,
    //         "onBoardingBvn": "22951789003",
    //         "agentUserId": "Agent001",
    //         "onboardingStatus": "COMPLETE",
    //         "onboardingFormUUID": "Pytuyi78nuuh1921",
    //         "gender": "MALE",
    //         "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //         "dateOfBirth": "2001-01-12",
    //         "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //         "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "accountNumbers": null,
    //         "passportFileDTO": null,
    //         "hasSuppliedAddressInfo": true,
    //         "hasSuppliedAddressProof": false,
    //         "hasSuppliedIdentificationInfo": false,
    //         "hasSuppliedIdentificationProof": false,
    //         "hasSuppliedAdditionalInfo": true,
    //         "hasSuppliedNextOfKinInfo": true,
    //         "reuploadID": true,
    //         "reuploadIDDeclineReason": null,
    //         "reuploadProofOfAddress": true,
    //         "reuploadProofOfAddressDeclineReason": null,
    //         "agentProvidingAddressProof": false,
    //         "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "generatedAgentAddressProofLatitude": null,
    //         "generatedAgentAddressProofLongitude": null,
    //         "addressProofFromCBA": null,
    //         "identificationScannedImageFromCBA": null,
    //         "customerIDInfo": null,
    //         "customerAddressInfo": null,
    //         "addressFileDTO": null,
    //         "identificationFileDTO": null,
    //         "addressVisitationFormFileDTO": null,
    //         "generatedAddressFileDTO": null,
    //         "verifiedAddressFileDTO": null,
    //         "verifiedIdentificationFileDTO": null,
    //         "branchName": null,
    //         "bvnVerified": false,
    //         "addressVerified": true,
    //         "identificationVerified": true,
    //         "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "branchCode": null,
    //         "emailAddresseeMap": {
    //           "oloruntobatoba@test.com": "AGHO ADRIAN "
    //         }
    //       },
    //       "cbaCustomerId": "1348799653315575808",
    //       "bankBranchId": 1,
    //       "accountName": "AGHO ADRIAN ",
    //       "currencyCode": "NGN",
    //       "accountNumber": "8000018402",
    //       "phoneNumber": "2348155198258",
    //       "email": "peguda1@teamapt.com",
    //       "address": null,
    //       "openingDate": "2021-01-12T01:11:12",
    //       "alternateAccountNumber": null,
    //       "accountType": "SAVINGS",
    //       "bvn": "22951789003",
    //       "accountBalance": null,
    //       "schemeCode": {
    //         "id": 7,
    //         "name": "MTC5",
    //         "description": "Customer indemnity",
    //         "code": "MTC5",
    //         "accountProvider": {
    //           "id": 1,
    //           "name": "Moniepoint",
    //           "centralBankCode": "950515",
    //           "aptentRoutingKey": "950515",
    //           "country": {
    //             "id": 1,
    //             "code": "NG",
    //             "name": "Nigeria",
    //             "postCode": "234",
    //             "isoCode": null,
    //             "base64Icon": null,
    //             "active": true,
    //             "timeAdded": null,
    //             "states": null,
    //             "nationality": "Nigerian"
    //           },
    //           "customerRMNodeType": "RELATIONSHIP_MANAGER",
    //           "customerAccountRMNodeType": "RELATIONSHIP_MANAGER",
    //           "unsupportedFeatures": null
    //         },
    //         "unsupportedFeatures": [],
    //         "customerType": "RETAIL",
    //         "classification": null,
    //         "timeAdded": "2021-07-05T17:04:43.27",
    //         "defaultAccountRole": null,
    //         "schemeGroup": "MONNIFY_INDEMNITY",
    //         "groupOrder": 6
    //       },
    //       "validated": true,
    //       "relationshipManagerNodeGuid": null,
    //       "relationshipManagerUserId": null,
    //       "active": true,
    //       "unsupportedFeatures": null,
    //       "timeAdded": "2021-01-12T03:11:10",
    //       "multipleDebit": false,
    //       "operationalAccount": null,
    //       "ussdProfile": null,
    //       "blocked": false,
    //       "blockReason": null,
    //       "blockedBy": null,
    //       "blockedTime": null,
    //       "referralCode": null,
    //       "emailAddresseeMap": {
    //         "peguda1@teamapt.com": "AGHO ADRIAN ",
    //         "oloruntobatoba@test.com": "AGHO ADRIAN "
    //       }
    //     },
    //     "active": true
    //   }
    // },
    // {
    //   "id": 8,
    //   "createdOn": "2021-11-03T12:41:03.000+0000",
    //   "lastModifiedOn": "2021-11-03T13:41:03",
    //   "deleted": false,
    //   "createdBy": "22951789003",
    //   "lastModifiedBy": "22951789003",
    //   "version": 0,
    //   "customer": {
    //     "id": 10,
    //     "name": "AGHO ADRIAN ",
    //     "description": null,
    //     "primaryCbaCustomerId": "1348799653315575808",
    //     "email": "oloruntobatoba@test.com",
    //     "mobileNo": "2348091614127",
    //     "timeAdded": "2021-01-12T03:11:09.681",
    //     "active": true,
    //     "title": "Mr",
    //     "headOffice": null,
    //     "relationshipManagerUserId": null,
    //     "relationshipManagerNodeGuid": null,
    //     "onBoardingBvn": "22951789003",
    //     "agentUserId": "Agent001",
    //     "onboardingStatus": "COMPLETE",
    //     "onboardingFormUUID": "Pytuyi78nuuh1921",
    //     "gender": "MALE",
    //     "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //     "dateOfBirth": "2001-01-12",
    //     "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //     "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "accountNumbers": null,
    //     "passportFileDTO": null,
    //     "hasSuppliedAddressInfo": true,
    //     "hasSuppliedAddressProof": false,
    //     "hasSuppliedIdentificationInfo": false,
    //     "hasSuppliedIdentificationProof": false,
    //     "hasSuppliedAdditionalInfo": true,
    //     "hasSuppliedNextOfKinInfo": true,
    //     "reuploadID": true,
    //     "reuploadIDDeclineReason": null,
    //     "reuploadProofOfAddress": true,
    //     "reuploadProofOfAddressDeclineReason": null,
    //     "agentProvidingAddressProof": false,
    //     "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "generatedAgentAddressProofLatitude": null,
    //     "generatedAgentAddressProofLongitude": null,
    //     "addressProofFromCBA": null,
    //     "identificationScannedImageFromCBA": null,
    //     "customerIDInfo": null,
    //     "customerAddressInfo": null,
    //     "addressFileDTO": null,
    //     "identificationFileDTO": null,
    //     "addressVisitationFormFileDTO": null,
    //     "generatedAddressFileDTO": null,
    //     "verifiedAddressFileDTO": null,
    //     "verifiedIdentificationFileDTO": null,
    //     "branchName": null,
    //     "bvnVerified": false,
    //     "addressVerified": true,
    //     "identificationVerified": true,
    //     "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //     "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //     "branchCode": null,
    //     "emailAddresseeMap": {
    //       "oloruntobatoba@test.com": "AGHO ADRIAN "
    //     }
    //   },
    //   "flexVersion": "1.0.0",
    //   "cbaAccountNuban": "8000001489",
    //   "interestRate": 0,
    //   "totalSavings": 0,
    //   "totalAccruedInterest": 0,
    //   "totalAppliedPenalties": 0,
    //   "flexSavingConfig": {
    //     "id": 9,
    //     "createdOn": "2021-11-03T12:40:50.000+0000",
    //     "lastModifiedOn": "2021-11-03T13:40:50",
    //     "deleted": false,
    //     "createdBy": "22951789003",
    //     "lastModifiedBy": "22951789003",
    //     "version": 0,
    //     "flexSaveType": "AUTOMATIC",
    //     "flexSaveMode": "MONTHLY",
    //     "contributionWeekDay": null,
    //     "contributionMonthDay": 31,
    //     "duration": 1,
    //     "contributionAmount": 1001,
    //     "contributionAccount": {
    //       "id": 4,
    //       "customer": {
    //         "id": 10,
    //         "name": "AGHO ADRIAN ",
    //         "description": null,
    //         "primaryCbaCustomerId": "1348799653315575808",
    //         "email": "oloruntobatoba@test.com",
    //         "mobileNo": "2348091614127",
    //         "timeAdded": "2021-01-12T03:11:09.681",
    //         "active": true,
    //         "title": "Mr",
    //         "headOffice": null,
    //         "relationshipManagerUserId": null,
    //         "relationshipManagerNodeGuid": null,
    //         "onBoardingBvn": "22951789003",
    //         "agentUserId": "Agent001",
    //         "onboardingStatus": "COMPLETE",
    //         "onboardingFormUUID": "Pytuyi78nuuh1921",
    //         "gender": "MALE",
    //         "customerPassportUUID": "Q8976tyhg6un89181uoj",
    //         "dateOfBirth": "2001-01-12",
    //         "utilityBillUUID": "Q8976tyhg6un89181uoj",
    //         "identificationUUID": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "accountNumbers": null,
    //         "passportFileDTO": null,
    //         "hasSuppliedAddressInfo": true,
    //         "hasSuppliedAddressProof": false,
    //         "hasSuppliedIdentificationInfo": false,
    //         "hasSuppliedIdentificationProof": false,
    //         "hasSuppliedAdditionalInfo": true,
    //         "hasSuppliedNextOfKinInfo": true,
    //         "reuploadID": true,
    //         "reuploadIDDeclineReason": null,
    //         "reuploadProofOfAddress": true,
    //         "reuploadProofOfAddressDeclineReason": null,
    //         "agentProvidingAddressProof": false,
    //         "generatedAgentAddressProofUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "generatedAgentAddressProofLatitude": null,
    //         "generatedAgentAddressProofLongitude": null,
    //         "addressProofFromCBA": null,
    //         "identificationScannedImageFromCBA": null,
    //         "customerIDInfo": null,
    //         "customerAddressInfo": null,
    //         "addressFileDTO": null,
    //         "identificationFileDTO": null,
    //         "addressVisitationFormFileDTO": null,
    //         "generatedAddressFileDTO": null,
    //         "verifiedAddressFileDTO": null,
    //         "verifiedIdentificationFileDTO": null,
    //         "branchName": null,
    //         "bvnVerified": false,
    //         "addressVerified": true,
    //         "identificationVerified": true,
    //         "accountOpeningFormRef": "ba82eaef-3c4d-4230-9f80-7854c84a9a87",
    //         "addressVisitationRequestFormUUID": "e6f2e987-b02e-4b41-8a40-85d7563739b6hg",
    //         "branchCode": null,
    //         "emailAddresseeMap": {
    //           "oloruntobatoba@test.com": "AGHO ADRIAN "
    //         }
    //       },
    //       "cbaCustomerId": "1348799653315575808",
    //       "bankBranchId": 1,
    //       "accountName": "AGHO ADRIAN ",
    //       "currencyCode": "NGN",
    //       "accountNumber": "8000018402",
    //       "phoneNumber": "2348155198258",
    //       "email": "peguda1@teamapt.com",
    //       "address": null,
    //       "openingDate": "2021-01-12T01:11:12",
    //       "alternateAccountNumber": null,
    //       "accountType": "SAVINGS",
    //       "bvn": "22951789003",
    //       "accountBalance": null,
    //       "schemeCode": {
    //         "id": 7,
    //         "name": "MTC5",
    //         "description": "Customer indemnity",
    //         "code": "MTC5",
    //         "accountProvider": {
    //           "id": 1,
    //           "name": "Moniepoint",
    //           "centralBankCode": "950515",
    //           "aptentRoutingKey": "950515",
    //           "country": {
    //             "id": 1,
    //             "code": "NG",
    //             "name": "Nigeria",
    //             "postCode": "234",
    //             "isoCode": null,
    //             "base64Icon": null,
    //             "active": true,
    //             "timeAdded": null,
    //             "states": null,
    //             "nationality": "Nigerian"
    //           },
    //           "customerRMNodeType": "RELATIONSHIP_MANAGER",
    //           "customerAccountRMNodeType": "RELATIONSHIP_MANAGER",
    //           "unsupportedFeatures": null
    //         },
    //         "unsupportedFeatures": [],
    //         "customerType": "RETAIL",
    //         "classification": null,
    //         "timeAdded": "2021-07-05T17:04:43.27",
    //         "defaultAccountRole": null,
    //         "schemeGroup": "MONNIFY_INDEMNITY",
    //         "groupOrder": 6
    //       },
    //       "validated": true,
    //       "relationshipManagerNodeGuid": null,
    //       "relationshipManagerUserId": null,
    //       "active": true,
    //       "unsupportedFeatures": null,
    //       "timeAdded": "2021-01-12T03:11:10",
    //       "multipleDebit": false,
    //       "operationalAccount": null,
    //       "ussdProfile": null,
    //       "blocked": false,
    //       "blockReason": null,
    //       "blockedBy": null,
    //       "blockedTime": null,
    //       "referralCode": null,
    //       "emailAddresseeMap": {
    //         "peguda1@teamapt.com": "AGHO ADRIAN ",
    //         "oloruntobatoba@test.com": "AGHO ADRIAN "
    //       }
    //     },
    //     "active": true
    //   }
    // }
  ],
  "errors": []
};