name: moniepoint_flutter
description: Moniepoint Customer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.5.0
  rxdart: ^0.26.0
  flutter_svg: ^0.22.0
  provider: ^5.0.0-nullsafety.1
  retrofit: ^2.0.0-beta1
  logger: any
  url_launcher: ^6.0.3
  uuid: ^3.0.4
  flutter_dotenv: ^2.1.0
  dio: ^4.0.0-beta7
  get_it: ^6.0.0
  mockito: ^5.0.3
  flutter_spinkit: "^5.0.0"
  camera: ^0.8.1
  path_provider: ^2.0.1
  path: ^1.8.0
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  device_info: ^2.0.0
  signature: ^4.0.2
  permission_handler: ^7.0.0
  flutter_inner_drawer: ^1.0.0+1
  lottie: ^1.0.1
  shimmer: ^2.0.0
  share: ^2.0.1
  floor: ^1.1.0
  dotted_border: ^2.0.0
  flutter_image_compress: ^1.0.0
  file_picker: ^3.0.1
  collection: ^1.15.0
  google_maps_flutter: ^2.0.6
  geolocator: ^7.0.3
  synchronized: ^3.0.0
  open_file: ^3.2.1
  contacts_service: ^0.6.1
  drawerbehavior: ^2.1.2
  firebase_core: "^1.3.0"
  firebase_crashlytics: "^2.0.6"
  flutter_html: ^2.1.0
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_downloader: ^1.6.0

dependency_overrides:
  retrofit:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: annotation
      ref: master

dev_dependencies:
  test: ^1.16.8
#  flutter_test:
#    sdk: flutter
  retrofit_generator:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      path: generator
      ref: master
  build_runner: any
  json_serializable: ^4.0.3
  floor_generator: ^1.1.0


flutter_icons:
  android: false
  ios: true
  image_path: "res/drawables/ios_launcher_icon.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - res/drawables/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
          weight: 400
    - family: CircularStd
      fonts:
        - asset: res/fonts/default_font_bold.ttf
          weight: 600
        - asset: res/fonts/default_font_medium.ttf
          weight: 500
        - asset: res/fonts/default_font_regular.ttf
          weight: 400
    - family: CustomFont
      fonts:
        - asset: res/fonts/custom_icons.ttf
    - family: CustomIcons2
      fonts:
        - asset: res/fonts/custom_icons_2.ttf
    - family: Ocra
      fonts:
        - asset: res/fonts/ocraextended.ttf
