/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomFont
///      fonts:
///       - asset: fonts/custom_icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomFont {
  CustomFont._();

  static const _kFontFam = 'CustomFont';
  static const String? _kFontPkg = null;

  static const IconData username_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bankIcon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropDown = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_question = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question_mark = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
