/// Flutter icons CustomIcons2
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons2
///      fonts:
///       - asset: fonts/CustomIcons2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons2 {
  CustomIcons2._();

  static const _kFontFam = 'CustomIcons2';
  static const String? _kFontPkg = null;

  static const IconData password = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData username = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
