class Routes {
  static const LOGIN  = "/login";
  static const REGISTER_EXISTING_ACCOUNT  = "REGISTER_EXISTING_ACCOUNT";
  static const REGISTER_NEW_ACCOUNT  = "REGISTER_NEW_ACCOUNT";
  static const ACCOUNT_RECOVERY  = "ACCOUNT_RECOVERY";
  static const DASHBOARD  = "DASHBOARD";
  static const ACCOUNT_UPDATE  = "ACCOUNT_UPDATE";
  static const LIVELINESS  = "LIVELINESS";
  static const TRANSFER  = "TRANSFER";
  static const AIRTIME  = "AIRTIME";
  static const AIRTIME_DETAIL  = "AIRTIME_DETAIL";
  static const BILL  = "BILL";
  static const BILL_DETAIL  = "BILL_DETAIL";
  static const TRANSFER_DETAIL  = "TRANSFER_DETAIL";
  static const ACCOUNT_TRANSACTIONS  = "ACCOUNT_TRANSACTIONS";
  static const ACCOUNT_TRANSACTIONS_DETAIL  = "ACCOUNT_TRANSACTIONS_DETAIL";
  static const SETTINGS  = "SETTINGS";
  static const MANAGED_BENEFICIARIES  = "MANAGED_BENEFICIARIES";
  static const SUPPORT  = "SUPPORT";
  static const BRANCHES  = "BRANCHES";
  static const BRANCHES_SEARCH  = "BRANCHES_SEARCH";
  static const CARDS  = "CARDS";
  static const CONTACTS  = "CONTACTS";
  static const SELECT_AIRTIME_BENEFICIARY  = "SELECT_AIRTIME_BENEFICIARY";
  static const SELECT_TRANSFER_BENEFICIARY  = "SELECT_TRANSFER_BENEFICIARY";
  static const SELECT_BILL_BENEFICIARY  = "SELECT_BILL_BENEFICIARY";


}