class Routes {
  static const REGISTER_EXISTING_ACCOUNT  = "REGISTER_EXISTING_ACCOUNT";
  static const REGISTER_NEW_ACCOUNT  = "REGISTER_NEW_ACCOUNT";
  static const ACCOUNT_RECOVERY  = "ACCOUNT_RECOVERY";
  static const DASHBOARD  = "DASHBOARD";
  static const ACCOUNT_UPDATE  = "ACCOUNT_UPDATE";
  static const LIVELINESS  = "LIVELINESS";
  static const TRANSFER  = "TRANSFER";

}